In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
data=pd.read_csv("courier_data.csv")

In [22]:
data.head()

,Delivery_ID,Rider_ID,Shift_Hour,Cumulative_Deliveries,Has_Elevator,Building_Floor,Traffic_Density,Delay_From_Target_Min,Burnout_Score
0,f98707cc,RIDER_103,9,14,1,7,Medium,-2.0,87
1,1a059f97,RIDER_093,5,2,1,10,Medium,4.2,47
2,09d083f7,RIDER_015,2,21,0,5,Medium,-1.0,85
3,1b288c51,RIDER_107,3,4,1,5,Low,3.1,36
4,067ac1d9,RIDER_072,4,19,1,1,Low,5.3,61

In [25]:
data.describe()

,Shift_Hour,Cumulative_Deliveries,Has_Elevator,Building_Floor,Delay_From_Target_Min,Burnout_Score
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.976800,12.554800,0.687900,5.003600,2.051280,71.507000
std,2.577387,6.902069,0.463374,3.139263,3.993087,20.019256
min,1.000000,1.000000,0.000000,0.000000,-11.900000,16.000000
25%,3.000000,7.000000,0.000000,2.000000,-0.600000,56.000000
50%,5.000000,13.000000,1.000000,5.000000,2.000000,71.000000
75%,7.000000,19.000000,1.000000,8.000000,4.800000,88.000000
max,9.000000,24.000000,1.000000,10.000000,15.900000,100.000000

In [33]:
#Convert categorical text (Traffic_Density) into numerical columns (0 and 1)
df= pd.get_dummies(data, columns=['Traffic_Density'], drop_first=True)

In [36]:
x = df.drop(columns=['Delivery_ID', 'Rider_ID', 'Burnout_Score'])
y = df['Burnout_Score']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [42]:
lr=LinearRegression()
rf=RandomForestRegressor(n_estimators=100, random_state=42)

In [43]:
lr_model=lr.fit(x_train,y_train)
rf_model=rf.fit(x_train,y_train)

In [44]:
lr_preds=lr_model.predict(x_test)
rf_preds=rf_model.predict(x_test)

In [45]:
print("--- Linear Regression Performance ---")
print(f"R2 Score: {r2_score(y_test, lr_preds):.4f}")
print(f"RMSE (Root Mean Squared Error): {np.sqrt(mean_squared_error(y_test, lr_preds)):.2f} points")


print("\n--- Random Forest Regressor Performance ---")
print(f"R2 Score: {r2_score(y_test, rf_preds):.4f}")
print(f"RMSE (Root Mean Squared Error): {np.sqrt(mean_squared_error(y_test, rf_preds)):.2f} points")

--- Linear Regression Performance ---
R2 Score: 0.7860
RMSE (Root Mean Squared Error): 9.31 points

--- Random Forest Regressor Performance ---
R2 Score: 0.9517
RMSE (Root Mean Squared Error): 4.42 points

In [47]:
import joblib
joblib.dump(rf_model, 'burnout_rf_model.pkl')

['burnout_rf_model.pkl']

In [52]:
try:
    rf_model = joblib.load('burnout_rf_model.pkl')
    print("Model loaded successfully!")
except:
    print("Model file not found. Please make sure rf_model is in memory.")

incoming_orders = pd.DataFrame({
    'Shift_Hour': [7, 7, 7, 7, 7],
    'Cumulative_Deliveries': [20, 21, 22, 23, 24],
    'Has_Elevator': [0, 1, 0, 1, 0],
    'Building_Floor': [5, 2, 4, 1, 6],
    'Delay_From_Target_Min': [5, 2, 8, 1, 10],
    'Traffic_Density_Low': [0, 1, 0, 0, 0],    # Trafiğin az olduğu durumlar için 1
    'Traffic_Density_Medium': [0, 0, 1, 1, 0]  # Trafiğin orta olduğu durumlar için 1
})


burnout_predictions = rf_model.predict(incoming_orders)

print("--- NEW ORDERS: BURNOUT RISK ANALYSIS ---")
for i, score in enumerate(burnout_predictions):
    
    decision = "REJECT / REASSIGN" if score > 85 else "ACCEPT"
    print(f"Order {i+1}: Predicted Score: {score:.2f} -> Decision: {decision}")

Model loaded successfully!
--- NEW ORDERS: BURNOUT RISK ANALYSIS ---
Order 1: Predicted Score: 99.99 -> Decision: REJECT / REASSIGN
Order 2: Predicted Score: 73.84 -> Decision: ACCEPT
Order 3: Predicted Score: 99.96 -> Decision: REJECT / REASSIGN
Order 4: Predicted Score: 82.47 -> Decision: ACCEPT
Order 5: Predicted Score: 100.00 -> Decision: REJECT / REASSIGN

['Shift_Hour' 'Cumulative_Deliveries' 'Has_Elevator' 'Building_Floor'
 'Delay_From_Target_Min' 'Traffic_Density_Low' 'Traffic_Density_Medium']

In [53]:
data.head()

,Delivery_ID,Rider_ID,Shift_Hour,Cumulative_Deliveries,Has_Elevator,Building_Floor,Traffic_Density,Delay_From_Target_Min,Burnout_Score
0,f98707cc,RIDER_103,9,14,1,7,Medium,-2.0,87
1,1a059f97,RIDER_093,5,2,1,10,Medium,4.2,47
2,09d083f7,RIDER_015,2,21,0,5,Medium,-1.0,85
3,1b288c51,RIDER_107,3,4,1,5,Low,3.1,36
4,067ac1d9,RIDER_072,4,19,1,1,Low,5.3,61